apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-test-22nov-2 
  janus-idp.io/tekton: py-test-22nov-2
  backstage.io/kubernetes-id: py-test-22nov-2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-test-22nov-2
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  